# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4af2740afbae2d5f4788a62e3f970d4c3cd5263572a69a11d1c514b9558aa8486c0af4b1acfc2f350d2c872cb8816d24f66fb35525d93d0f23df4588a72cede4

test:
  secret_key_base: d293d3ecd3f7c2ed397783d24bb68a51c2dd56d6342a7ffc627e5fe8f067b184f076cd1c777802fa17c63f50f0d290a7f66abb2eb6c9382b32b40def05aabb4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
